#!/usr/bin/env python3
"""
Translation script for zh.json i18n file.
Updates untranslated English strings to Chinese while preserving proper nouns.
"""

import json
import re
from pathlib import Path

# Translation mapping - comprehensive list of UI strings and their Chinese translations
TRANSLATIONS = {
    # Common UI Elements
    "comment L": "评论 L",
    "Git repo": "Git 仓库",
    "MR !{{value0}}": "MR !{{value0}}",
    "Double-tap {{value0}}": "双击 {{value0}}",

    # Terminal Messages
    "No agent CLI detected — install one or pick a default agent in Settings.": "未检测到 Agent CLI — 请安装一个或在设置中选择默认 Agent。",
    "Could not build launch command for {{value0}}.": "无法为 {{value0}} 构建启动命令。",

    # Automations
    "Add project": "添加项目",
    "Adding project…": "正在添加项目…",
    "Choose automation host": "选择自动化主机",
    "No projects/folders match your search.": "没有匹配的项目/文件夹。",
    "Search projects/folders...": "搜索项目/文件夹...",
    "Retry source": "重试来源",
    "Automation source refreshed.": "自动化来源已刷新。",

    # Browser Pane
    "Could not open the downloaded file. It may have been moved or deleted.": "无法打开下载的文件。文件可能已被移动或删除。",
    "Could not show the downloaded file. It may have been moved or deleted.": "无法显示下载的文件。文件可能已被移动或删除。",
    "Downloading paused": "下载已暂停",
    "Download failed": "下载失败",
    "The downloaded file path is unavailable.": "下载的文件路径不可用。",

    # Crash Report
    "Attach recent diagnostic logs": "附加最近的诊断日志",
    "Failed to send crash report. Diagnostic ticket {{value0}} was uploaded but not linked.": "发送崩溃报告失败。诊断工单 {{value0}} 已上传但未关联。",
    "Sends a capped redacted log bundle with the report.": "随报告发送有限制的脱敏日志包。",
    "No automatic crash report was captured. You can still send details and include recent diagnostic logs when available.": "未捕获到自动崩溃报告。您仍然可以发送详细信息，并在可用时包含最近的诊断日志。",

    # Check Run Details
    "Failed jobs": "失败的作业",
    "No details are available for this check.": "此检查没有可用的详细信息。",
    "Loading check details…": "正在加载检查详情…",
    "workflow #": "工作流 #",
    "Timed out": "已超时",
    "Fix with AI": "使用 AI 修复",
    "Status:": "状态：",
    "Open details": "打开详情",
    "Check fix context unavailable": "检查修复上下文不可用",
    "Choose the agent and edit the full command input before launch.": "选择 Agent 并在启动前编辑完整的命令输入。",
    "Start the default AI agent to fix this check": "启动默认 AI Agent 以修复此检查",
    "Choose an agent for this check": "选择用于此检查的 Agent",
    "Choose agent to fix check": "选择修复检查的 Agent",
    "Check details are unavailable.": "检查详情不可用。",

    # Editor
    "Resize table of contents": "调整目录大小",
    "Paste is too large.": "粘贴内容过大。",
    "Select a workspace before launching an AI action.": "在启动 AI 操作前选择工作区。",
    "Started an AI agent for this check.": "已为此检查启动 AI Agent。",
    "Select a repository before launching an AI action.": "在启动 AI 操作前选择仓库。",
    "Open a PR or MR before launching an AI fix.": "在启动 AI 修复前打开 PR 或 MR。",
    "This check is not failing.": "此检查未失败。",

    # Mobile Emulator
    "Mobile emulator Orca CLI skill setup": "移动模拟器 Orca CLI 技能设置",
    "Mobile emulator Orca CLI skill install terminal": "移动模拟器 Orca CLI 技能安装终端",
    "Emulator keyboard paste failed because the device is not ready.": "模拟器键盘粘贴失败，因为设备未就绪。",
    "Paste is too large for emulator keyboard input.": "粘贴内容对于模拟器键盘输入来说过大。",
    "Emulator keyboard paste supports US keyboard text only.": "模拟器键盘粘贴仅支持美式键盘文本。",

    # Common Actions
    "Cancel": "取消",
    "Canceled": "已取消",
    "Cancelled": "已取消",
    "Close": "关闭",
    "Closed": "已关闭",
    "Closing...": "正在关闭...",
    "Open": "打开",
    "Opened": "已打开",
    "Opening...": "正在打开...",
    "Save": "保存",
    "Saving...": "正在保存...",
    "Delete": "删除",
    "Deleting...": "正在删除...",
    "Edit": "编辑",
    "Editing...": "正在编辑...",
    "Create": "创建",
    "Creating...": "正在创建...",
    "Update": "更新",
    "Updating...": "正在更新...",
    "Loading...": "加载中...",
    "Loading": "加载中",
    "Refresh": "刷新",
    "Refreshing...": "正在刷新...",
    "Retry": "重试",
    "Remove": "移除",
    "Removing...": "正在移除...",
    "Add": "添加",
    "Apply": "应用",
    "Applying...": "正在应用...",
    "Confirm": "确认",
    "Submit": "提交",
    "Submitting...": "正在提交...",
    "Send": "发送",
    "Sending...": "正在发送...",
    "Copy": "复制",
    "Copied": "已复制",
    "Paste": "粘贴",
    "Search": "搜索",
    "Searching...": "正在搜索...",
    "Filter": "筛选",
    "Filters": "筛选条件",
    "Clear": "清除",
    "Clear all": "全部清除",
    "Reset": "重置",
    "Restore": "恢复",
    "Restoring...": "正在恢复...",
    "Download": "下载",
    "Downloading...": "正在下载...",
    "Upload": "上传",
    "Uploading...": "正在上传...",
    "Import": "导入",
    "Export": "导出",
    "Show": "显示",
    "Hide": "隐藏",
    "Expand": "展开",
    "Collapse": "折叠",
    "Previous": "上一个",
    "Next": "下一个",
    "Back": "返回",
    "Forward": "前进",
    "More": "更多",
    "Less": "更少",
    "All": "全部",
    "None": "无",
    "Select": "选择",
    "Select all": "全选",
    "Deselect": "取消选择",
    "Deselect all": "取消全选",
    "Select none": "全不选",
    "Enable": "启用",
    "Disable": "禁用",
    "Enabled": "已启用",
    "Disabled": "已禁用",
    "Active": "活跃",
    "Inactive": "非活跃",
    "Pending": "待处理",
    "Completed": "已完成",
    "Failed": "失败",
    "Success": "成功",
    "Successful": "成功",
    "Error": "错误",
    "Warning": "警告",
    "Info": "信息",
    "Information": "信息",
    "Debug": "调试",
    "Trace": "跟踪",
    "Critical": "严重",
    "Fatal": "致命",
    "Unknown": "未知",
    "Other": "其他",
    "Default": "默认",
    "Custom": "自定义",
    "System": "系统",
    "User": "用户",
    "Admin": "管理员",
    "Guest": "访客",
    "Public": "公开",
    "Private": "私有",
    "Internal": "内部",
    "External": "外部",
    "Local": "本地",
    "Remote": "远程",
    "Source": "来源",
    "Target": "目标",
    "Destination": "目标",
    "Path": "路径",
    "Directory": "目录",
    "Folder": "文件夹",
    "File": "文件",
    "Files": "文件",
    "Name": "名称",
    "Title": "标题",
    "Description": "描述",
    "Summary": "摘要",
    "Details": "详情",
    "Content": "内容",
    "Text": "文本",
    "Value": "值",
    "Key": "键",
    "Type": "类型",
    "Category": "类别",
    "Tag": "标签",
    "Tags": "标签",
    "Label": "标签",
    "Labels": "标签",
    "Status": "状态",
    "State": "状态",
    "Priority": "优先级",
    "Severity": "严重程度",
    "Impact": "影响",
    "Risk": "风险",
    "Level": "级别",
    "Mode": "模式",
    "Option": "选项",
    "Options": "选项",
    "Setting": "设置",
    "Settings": "设置",
    "Configuration": "配置",
    "Preferences": "首选项",
    "Property": "属性",
    "Properties": "属性",
    "Attribute": "属性",
    "Attributes": "属性",
    "Parameter": "参数",
    "Parameters": "参数",
    "Argument": "参数",
    "Arguments": "参数",
    "Variable": "变量",
    "Variables": "变量",
    "Field": "字段",
    "Fields": "字段",
    "Column": "列",
    "Columns": "列",
    "Row": "行",
    "Rows": "行",
    "Cell": "单元格",
    "Cells": "单元格",
    "Item": "项",
    "Items": "项",
    "Entry": "条目",
    "Entries": "条目",
    "Record": "记录",
    "Records": "记录",
    "Element": "元素",
    "Elements": "元素",
    "Component": "组件",
    "Components": "组件",
    "Module": "模块",
    "Modules": "模块",
    "Package": "包",
    "Packages": "包",
    "Library": "库",
    "Libraries": "库",
    "Plugin": "插件",
    "Plugins": "插件",
    "Extension": "扩展",
    "Extensions": "扩展",
    "Theme": "主题",
    "Themes": "主题",
    "Template": "模板",
    "Templates": "模板",
    "Layout": "布局",
    "Layouts": "布局",
    "View": "视图",
    "Views": "视图",
    "Perspective": "透视图",
    "Perspectives": "透视图",
    "Panel": "面板",
    "Panels": "面板",
    "Tab": "标签页",
    "Tabs": "标签页",
    "Window": "窗口",
    "Windows": "窗口",
    "Dialog": "对话框",
    "Dialogs": "对话框",
    "Modal": "模态框",
    "Modals": "模态框",
    "Popup": "弹出框",
    "Popups": "弹出框",
    "Tooltip": "工具提示",
    "Tooltips": "工具提示",
    "Notification": "通知",
    "Notifications": "通知",
    "Message": "消息",
    "Messages": "消息",
    "Alert": "警报",
    "Alerts": "警报",
    "Confirmation": "确认",
    "Prompt": "提示",
    "Input": "输入",
    "Output": "输出",
    "Result": "结果",
    "Results": "结果",
    "Data": "数据",
    "Database": "数据库",
    "Cache": "缓存",
    "Storage": "存储",
    "Memory": "内存",
    "Disk": "磁盘",
    "Network": "网络",
    "Connection": "连接",
    "Connections": "连接",
    "Session": "会话",
    "Sessions": "会话",
    "Token": "令牌",
    "Tokens": "令牌",
    "Secret": "密钥",
    "Secrets": "密钥",
    "Password": "密码",
    "Passwords": "密码",
    "Credential": "凭证",
    "Credentials": "凭证",
    "Certificate": "证书",
    "Certificates": "证书",
    "License": "许可证",
    "Licenses": "许可证",
    "Permission": "权限",
    "Permissions": "权限",
    "Role": "角色",
    "Roles": "角色",
    "Group": "组",
    "Groups": "组",
    "Team": "团队",
    "Teams": "团队",
    "Organization": "组织",
    "Organizations": "组织",
    "Project": "项目",
    "Projects": "项目",
    "Repository": "仓库",
    "Repositories": "仓库",
    "Workspace": "工作区",
    "Workspaces": "工作区",
    "Worktree": "工作树",
    "Worktrees": "工作树",
    "Branch": "分支",
    "Branches": "分支",
    "Commit": "提交",
    "Commits": "提交",
    "Change": "更改",
    "Changes": "更改",
    "Diff": "差异",
    "Diffs": "差异",
    "Merge": "合并",
    "Merges": "合并",
    "Rebase": "变基",
    "Cherry-pick": "拣选",
    "Revert": "还原",
    "Checkout": "检出",
    "Clone": "克隆",
    "Fork": "复刻",
    "Pull": "拉取",
    "Push": "推送",
    "Fetch": "获取",
    "Stash": "贮藏",
    "Stashes": "贮藏",
    "Release": "发布",
    "Releases": "发布",
    "Version": "版本",
    "Versions": "版本",
    "Build": "构建",
    "Builds": "构建",
    "Deployment": "部署",
    "Deployments": "部署",
    "Environment": "环境",
    "Environments": "环境",
    "Stage": "阶段",
    "Stages": "阶段",
    "Production": "生产",
    "Staging": "预发布",
    "Development": "开发",
    "Test": "测试",
    "Testing": "测试",
    "Preview": "预览",
    "Draft": "草稿",
    "Published": "已发布",
    "Unpublished": "未发布",
    "Archived": "已归档",
    "Locked": "已锁定",
    "Unlocked": "未锁定",
    "Blocked": "已阻止",
    "Unblocked": "未阻止",
    "Suspended": "已暂停",
    "Resumed": "已恢复",
    "Scheduled": "已计划",
    "Running": "运行中",
    "Started": "已启动",
    "Stopped": "已停止",
    "Paused": "已暂停",
    "Waiting": "等待中",
    "Queued": "队列中",
    "Processing": "处理中",
    "Processed": "已处理",
    "Generated": "已生成",
    "Generating...": "正在生成...",
    "Validated": "已验证",
    "Validating...": "正在验证...",
    "Verified": "已验证",
    "Verifying...": "正在验证...",
    "Approved": "已批准",
    "Approving...": "正在批准...",
    "Rejected": "已拒绝",
    "Rejecting...": "正在拒绝...",
    "Accepted": "已接受",
    "Accepting...": "正在接受...",
    "Declined": "已拒绝",
    "Declining...": "正在拒绝...",
    "Assigned": "已分配",
    "Assigning...": "正在分配...",
    "Unassigned": "未分配",
    "Resolved": "已解决",
    "Resolving...": "正在解决...",
    "Unresolved": "未解决",
    "Fixed": "已修复",
    "Fixing...": "正在修复...",
    "Broken": "已损坏",
    "Working": "正常",
    "Online": "在线",
    "Offline": "离线",
    "Connected": "已连接",
    "Connecting...": "正在连接...",
    "Disconnected": "已断开",
    "Disconnecting...": "正在断开...",
    "Reconnect": "重新连接",
    "Reconnecting...": "正在重新连接...",
    "Timeout": "超时",
    "Expired": "已过期",
    "Available": "可用",
    "Unavailable": "不可用",
    "Visible": "可见",
    "Hidden": "隐藏",
    "Shown": "已显示",
    "Read": "已读",
    "Unread": "未读",
    "Seen": "已查看",
    "Unseen": "未查看",
    "New": "新建",
    "Old": "旧",
    "Recent": "最近",
    "Latest": "最新",
    "Current": "当前",
    "First": "第一",
    "Last": "最后",
    "Early": "早期",
    "Late": "晚期",
    "Soon": "很快",
    "Later": "稍后",
    "Now": "现在",
    "Today": "今天",
    "Yesterday": "昨天",
    "Tomorrow": "明天",
    "Morning": "早上",
    "Afternoon": "下午",
    "Evening": "晚上",
    "Night": "晚上",
    "Hour": "小时",
    "Hours": "小时",
    "Minute": "分钟",
    "Minutes": "分钟",
    "Second": "秒",
    "Seconds": "秒",
    "Day": "天",
    "Days": "天",
    "Week": "周",
    "Weeks": "周",
    "Month": "月",
    "Months": "月",
    "Year": "年",
    "Years": "年",
    "Time": "时间",
    "Date": "日期",
    "Datetime": "日期时间",
    "Timestamp": "时间戳",
    "Timezone": "时区",
    "Calendar": "日历",
    "Schedule": "计划",
    "Event": "事件",
    "Events": "事件",
    "Task": "任务",
    "Tasks": "任务",
    "Job": "作业",
    "Jobs": "作业",
    "Operation": "操作",
    "Operations": "操作",
    "Action": "动作",
    "Actions": "动作",
    "Activity": "活动",
    "Activities": "活动",
    "Process": "进程",
    "Processes": "进程",
    "Thread": "线程",
    "Threads": "线程",
    "Service": "服务",
    "Services": "服务",
    "Daemon": "守护进程",
    "Daemons": "守护进程",
    "Server": "服务器",
    "Servers": "服务器",
    "Client": "客户端",
    "Clients": "客户端",
    "Host": "主机",
    "Hosts": "主机",
    "Port": "端口",
    "Ports": "端口",
    "Address": "地址",
    "Addresses": "地址",
    "Endpoint": "端点",
    "Endpoints": "端点",
    "Route": "路由",
    "Routes": "路由",
    "Request": "请求",
    "Requests": "请求",
    "Response": "响应",
    "Responses": "响应",
    "Header": "头部",
    "Headers": "头部",
    "Body": "主体",
    "Bodies": "主体",
    "Payload": "载荷",
    "Payloads": "载荷",
    "Query": "查询",
    "Queries": "查询",
    "Params": "参数",
    "Fragment": "片段",
    "Fragments": "片段",
    "Scheme": "协议",
    "Schemes": "协议",
    "Protocol": "协议",
    "Protocols": "协议",
    "Method": "方法",
    "Methods": "方法",
    "Function": "函数",
    "Functions": "函数",
    "Class": "类",
    "Classes": "类",
    "Interface": "接口",
    "Interfaces": "接口",
    "Enum": "枚举",
    "Enums": "枚举",
    "Struct": "结构体",
    "Structs": "结构体",
    "Namespace": "命名空间",
    "Namespaces": "命名空间",
    "Import": "导入",
    "Imports": "导入",
    "Export": "导出",
    "Exports": "导出",
    "Include": "包含",
    "Includes": "包含",
    "Exclude": "排除",
    "Excludes": "排除",
    "Contain": "包含",
    "Contains": "包含",
    "Match": "匹配",
    "Matches": "匹配",
    "Sort": "排序",
    "Sorts": "排序",
    "Order": "顺序",
    "Orders": "顺序",
    "Group": "分组",
    "Groups": "分组",
    "Join": "连接",
    "Joins": "连接",
    "Intersect": "交集",
    "Intersects": "交集",
    "Limit": "限制",
    "Limits": "限制",
    "Offset": "偏移",
    "Offsets": "偏移",
    "Page": "页",
    "Pages": "页",
    "Pagination": "分页",
    "Cursor": "游标",
    "Cursors": "游标",
    "Index": "索引",
    "Indexes": "索引",
    "Indices": "索引",
    "Foreign key": "外键",
    "Foreign keys": "外键",
    "Primary key": "主键",
    "Primary keys": "主键",
    "Unique": "唯一",
    "Constraint": "约束",
    "Constraints": "约束",
    "Trigger": "触发器",
    "Triggers": "触发器",
    "Procedure": "存储过程",
    "Procedures": "存储过程",
    "Sequence": "序列",
    "Sequences": "序列",
    "Schema": "模式",
    "Schemas": "模式",
    "Catalog": "目录",
    "Catalogs": "目录",
    "Tablespace": "表空间",
    "Tablespaces": "表空间",
    "Partition": "分区",
    "Partitions": "分区",
    "Shard": "分片",
    "Shards": "分片",
    "Replica": "副本",
    "Replicas": "副本",
    "Backup": "备份",
    "Backups": "备份",
    "Snapshot": "快照",
    "Snapshots": "快照",
    "Sync": "同步",
    "Syncs": "同步",
    "Replicate": "复制",
    "Replicates": "复制",
    "Replicating...": "正在复制...",
    "Migrate": "迁移",
    "Migrates": "迁移",
    "Migrating...": "正在迁移...",
    "Transform": "转换",
    "Transforms": "转换",
    "Transforming...": "正在转换...",
    "Normalize": "规范化",
    "Normalizes": "规范化",
    "Normalizing...": "正在规范化...",
    "Denormalize": "反规范化",
    "Denormalizes": "反规范化",
    "Compress": "压缩",
    "Compresses": "压缩",
    "Compressing...": "正在压缩...",
    "Decompress": "解压缩",
    "Decompresses": "解压缩",
    "Decompressing...": "正在解压缩...",
    "Encrypt": "加密",
    "Encrypts": "加密",
    "Encrypting...": "正在加密...",
    "Decrypt": "解密",
    "Decrypts": "解密",
    "Decrypting...": "正在解密...",
    "Encode": "编码",
    "Encodes": "编码",
    "Encoding...": "正在编码...",
    "Decode": "解码",
    "Decodes": "解码",
    "Decoding...": "正在解码...",
    "Hash": "哈希",
    "Hashes": "哈希",
    "Hashing...": "正在哈希...",
    "Sign": "签名",
    "Signs": "签名",
    "Signing...": "正在签名...",
    "Parse": "解析",
    "Parses": "解析",
    "Parsing...": "正在解析...",
    "Serialize": "序列化",
    "Serializes": "序列化",
    "Serializing...": "正在序列化...",
    "Deserialize": "反序列化",
    "Deserializes": "反序列化",
    "Deserializing...": "正在反序列化...",
    "Format": "格式化",
    "Formats": "格式化",
    "Formatting...": "正在格式化...",
    "Lint": "检查",
    "Lints": "检查",
    "Linting...": "正在检查...",
    "Analyze": "分析",
    "Analyzes": "分析",
    "Analyzing...": "正在分析...",
    "Optimize": "优化",
    "Optimizes": "优化",
    "Optimizing...": "正在优化...",
    "Refactor": "重构",
    "Refactors": "重构",
    "Refactoring...": "正在重构...",
    "Debug": "调试",
    "Debugging...": "正在调试...",
    "Tracing...": "正在跟踪...",
    "Profile": "性能分析",
    "Profiling...": "正在性能分析...",
    "Benchmark": "基准测试",
    "Benchmarking...": "正在基准测试...",
    "Testing...": "正在测试...",
    "Mock": "模拟",
    "Mocks": "模拟",
    "Mocking...": "正在模拟...",
    "Stub": "存根",
    "Stubs": "存根",
    "Fake": "伪造",
    "Fakes": "伪造",
    "Spy": "监视",
    "Spies": "监视",
    "Assert": "断言",
    "Asserts": "断言",
    "Assertion": "断言",
    "Assertions": "断言",
    "Expect": "期望",
    "Expects": "期望",
    "Expectation": "期望",
    "Expectations": "期望",
    "Verify": "验证",
    "Verifies": "验证",
    "Verification": "验证",
    "Verifications": "验证",
    "Validate": "验证",
    "Validates": "验证",
    "Validation": "验证",
    "Validations": "验证",
    "Inspection": "检查",
    "Inspections": "检查",
    "Review": "审阅",
    "Reviews": "审阅",
    "Revision": "修订",
    "Revisions": "修订",
    "Edits": "编辑",
    "Editing...": "正在编辑...",
    "Modify": "修改",
    "Modifies": "修改",
    "Modifying...": "正在修改...",
    "Updates": "更新",
    "Updating...": "正在更新...",
    "Upgrade": "升级",
    "Upgrades": "升级",
    "Upgrading...": "正在升级...",
    "Downgrade": "降级",
    "Downgrades": "降级",
    "Downgrading...": "正在降级...",
    "Install": "安装",
    "Installs": "安装",
    "Installing...": "正在安装...",
    "Uninstall": "卸载",
    "Uninstalls": "卸载",
    "Uninstalling...": "正在卸载...",
    "Deploy": "部署",
    "Deploys": "部署",
    "Deploying...": "正在部署...",
    "Undeploy": "取消部署",
    "Undeploys": "取消部署",
    "Undeploying...": "正在取消部署...",
    "Provision": "配置",
    "Provisions": "配置",
    "Provisioning...": "正在配置...",
    "Deprovision": "取消配置",
    "Deprovisions": "取消配置",
    "Deprovisioning...": "正在取消配置...",
    "Configure": "配置",
    "Configures": "配置",
    "Configuring...": "正在配置...",
    "Reconfigure": "重新配置",
    "Reconfigures": "重新配置",
    "Reconfiguring...": "正在重新配置...",
    "Setup": "设置",
    "Setups": "设置",
    "Setting up...": "正在设置...",
    "Teardown": "拆卸",
    "Teardowns": "拆卸",
    "Tearing down...": "正在拆卸...",
    "Initialize": "初始化",
    "Initializes": "初始化",
    "Initializing...": "正在初始化...",
    "Finalize": "完成",
    "Finalizes": "完成",
    "Finalizing...": "正在完成...",
    "Prepare": "准备",
    "Prepares": "准备",
    "Preparing...": "正在准备...",
    "Cleanup": "清理",
    "Cleanups": "清理",
    "Cleaning up...": "正在清理...",
    "Starts": "开始",
    "Starting...": "正在开始...",
    "Begin": "开始",
    "Begins": "开始",
    "Beginning...": "正在开始...",
    "Initiate": "启动",
    "Initiates": "启动",
    "Initiating...": "正在启动...",
    "Launch": "启动",
    "Launches": "启动",
    "Launching...": "正在启动...",
    "Boot": "启动",
    "Boots": "启动",
    "Booting...": "正在启动...",
    "Startup": "启动",
    "Run": "运行",
    "Runs": "运行",
    "Running...": "正在运行...",
    "Execute": "执行",
    "Executes": "执行",
    "Executing...": "正在执行...",
    "Perform": "执行",
    "Performs": "执行",
    "Performing...": "正在执行...",
    "Conduct": "执行",
    "Conducts": "执行",
    "Conducting...": "正在执行...",
    "Carry out": "执行",
    "Carries out": "执行",
    "Carrying out...": "正在执行...",
    "Stops": "停止",
    "Stopping...": "正在停止...",
    "End": "结束",
    "Ends": "结束",
    "Ending...": "正在结束...",
    "Finish": "完成",
    "Finishes": "完成",
    "Finishing...": "正在完成...",
    "Complete": "完成",
    "Completes": "完成",
    "Completing...": "正在完成...",
    "Terminate": "终止",
    "Terminates": "终止",
    "Terminating...": "正在终止...",
    "Abort": "中止",
    "Aborts": "中止",
    "Aborting...": "正在中止...",
    "Canceling...": "正在取消...",
    "Halt": "暂停",
    "Halts": "暂停",
    "Halting...": "正在暂停...",
    "Pauses": "暂停",
    "Pausing...": "正在暂停...",
    "Resumes": "恢复",
    "Resuming...": "正在恢复...",
    "Continue": "继续",
    "Continues": "继续",
    "Continuing...": "正在继续...",
    "Proceed": "继续",
    "Proceeds": "继续",
    "Proceeding...": "正在继续...",
    "Advance": "前进",
    "Advances": "前进",
    "Advancing...": "正在前进...",
    "Progress": "进度",
    "Progresses": "进度",
    "Progressing...": "正在进度...",
    "Wait": "等待",
    "Waits": "等待",
    "Waiting...": "正在等待...",
    "Hold": "保持",
    "Holds": "保持",
    "Holding...": "正在保持...",
    "Stay": "停留",
    "Stays": "停留",
    "Staying...": "正在停留...",
    "Remain": "保持",
    "Remains": "保持",
    "Remaining...": "正在保持...",
    "Keep": "保持",
    "Keeps": "保持",
    "Keeping...": "正在保持...",
    "Maintain": "维护",
    "Maintains": "维护",
    "Maintaining...": "正在维护...",
    "Preserve": "保留",
    "Preserves": "保留",
    "Preserving...": "正在保留...",
    "Retain": "保留",
    "Retains": "保留",
    "Retaining...": "正在保留...",
    "Saves": "保存",
    "Saving...": "正在保存...",
    "Persist": "持久化",
    "Persists": "持久化",
    "Persisting...": "正在持久化...",
    "Store": "存储",
    "Stores": "存储",
    "Storing...": "正在存储...",
    "Load": "加载",
    "Loads": "加载",
    "Loading...": "正在加载...",
    "Fetches": "获取",
    "Fetching...": "正在获取...",
    "Retrieve": "检索",
    "Retrieves": "检索",
    "Retrieving...": "正在检索...",
    "Get": "获取",
    "Gets": "获取",
    "Getting...": "正在获取...",
    "Obtain": "获取",
    "Obtains": "获取",
    "Obtaining...": "正在获取...",
    "Acquire": "获取",
    "Acquires": "获取",
    "Acquiring...": "正在获取...",
    "Gain": "获得",
    "Gains": "获得",
    "Gaining...": "正在获得...",
    "Receive": "接收",
    "Receives": "接收",
    "Receiving...": "正在接收...",
    "Accept": "接受",
    "Accepts": "接受",
    "Accepting...": "正在接受...",
    "Take": "获取",
    "Takes": "获取",
    "Taking...": "正在获取...",
    "Collect": "收集",
    "Collects": "收集",
    "Collecting...": "正在收集...",
    "Gather": "收集",
    "Gathers": "收集",
    "Gathering...": "正在收集...",
    "Aggregate": "聚合",
    "Aggregates": "聚合",
    "Aggregating...": "正在聚合...",
    "Accumulate": "累积",
    "Accumulates": "累积",
    "Accumulating...": "正在累积...",
    "Compile": "编译",
    "Compiles": "编译",
    "Compiling...": "正在编译...",
    "Assemble": "组装",
    "Assembles": "组装",
    "Assembling...": "正在组装...",
    "Builds": "构建",
    "Building...": "正在构建...",
    "Construct": "构建",
    "Constructs": "构建",
    "Constructing...": "正在构建...",
    "Make": "创建",
    "Makes": "创建",
    "Making...": "正在创建...",
    "Creates": "创建",
    "Creating...": "正在创建...",
    "Generate": "生成",
    "Generates": "生成",
    "Generating...": "正在生成...",
    "Produce": "产生",
    "Produces": "产生",
    "Producing...": "正在产生...",
    "Render": "渲染",
    "Renders": "渲染",
    "Rendering...": "正在渲染...",
    "Draw": "绘制",
    "Draws": "绘制",
    "Drawing...": "正在绘制...",
    "Paint": "绘制",
    "Paints": "绘制",
    "Painting...": "正在绘制...",
    "Display": "显示",
    "Displays": "显示",
    "Displaying...": "正在显示...",
    "Shows": "显示",
    "Showing...": "正在显示...",
    "Present": "呈现",
    "Presents": "呈现",
    "Presenting...": "正在呈现...",
    "Visualize": "可视化",
    "Visualizes": "可视化",
    "Visualizing...": "正在可视化...",
    "Publish": "发布",
    "Publishes": "发布",
    "Publishing...": "正在发布...",
    "Releases": "发布",
    "Releasing...": "正在发布...",
    "Distribute": "分发",
    "Distributes": "分发",
    "Distributing...": "正在分发...",
    "Share": "分享",
    "Shares": "分享",
    "Sharing...": "正在分享...",
    "Broadcast": "广播",
    "Broadcasts": "广播",
    "Broadcasting...": "正在广播...",
    "Transmit": "传输",
    "Transmits": "传输",
    "Transmitting...": "正在传输...",
    "Transfer": "传输",
    "Transfers": "传输",
    "Transferring...": "正在传输...",
    "Move": "移动",
    "Moves": "移动",
    "Moving...": "正在移动...",
    "Shift": "移动",
    "Shifts": "移动",
    "Shifting...": "正在移动...",
    "Relocate": "重新定位",
    "Relocates": "重新定位",
    "Relocating...": "正在重新定位...",
    "Reposition": "重新定位",
    "Repositions": "重新定位",
    "Repositioning...": "正在重新定位...",
    "Copies": "复制",
    "Copying...": "正在复制...",
    "Duplicate": "复制",
    "Duplicates": "复制",
    "Duplicating...": "正在复制...",
    "Clones": "克隆",
    "Cloning...": "正在克隆...",
    "Replicates": "复制",
    "Replicating...": "正在复制...",
    "Reproduce": "重现",
    "Reproduces": "重现",
    "Reproducing...": "正在重现...",
    "Mirror": "镜像",
    "Mirrors": "镜像",
    "Mirroring...": "正在镜像...",
    "Reflect": "反射",
    "Reflects": "反射",
    "Reflecting...": "正在反射...",
    "Echo": "回显",
    "Echos": "回显",
    "Echoing...": "正在回显...",
    "Repeat": "重复",
    "Repeats": "重复",
    "Repeating...": "正在重复...",
    "Loop": "循环",
    "Loops": "循环",
    "Looping...": "正在循环...",
    "Iterate": "迭代",
    "Iterates": "迭代",
    "Iterating...": "正在迭代...",
    "Recurse": "递归",
    "Recurses": "递归",
    "Recursing...": "正在递归...",
    "Traverse": "遍历",
    "Traverses": "遍历",
    "Traversing...": "正在遍历...",
    "Navigate": "导航",
    "Navigates": "导航",
    "Navigating...": "正在导航...",
    "Browse": "浏览",
    "Browses": "浏览",
    "Browsing...": "正在浏览...",
    "Explore": "探索",
    "Explores": "探索",
    "Exploring...": "正在探索...",
    "Discover": "发现",
    "Discovers": "发现",
    "Discovering...": "正在发现...",
    "Find": "查找",
    "Finds": "查找",
    "Finding...": "正在查找...",
    "Searches": "搜索",
    "Searching...": "正在搜索...",
    "Seek": "寻找",
    "Seeks": "寻找",
    "Seeking...": "正在寻找...",
    "Hunt": "搜索",
    "Hunts": "搜索",
    "Hunting...": "正在搜索...",
    "Locate": "定位",
    "Locates": "定位",
    "Locating...": "正在定位...",
    "Pinpoint": "精确定位",
    "Pinpoints": "精确定位",
    "Pinpointing...": "正在精确定位...",
    "Detect": "检测",
    "Detects": "检测",
    "Detecting...": "正在检测...",
    "Sense": "感知",
    "Senses": "感知",
    "Sensing...": "正在感知...",
    "Feel": "感受",
    "Feels": "感受",
    "Feeling...": "正在感受...",
    "Perceive": "感知",
    "Perceives": "感知",
    "Perceiving...": "正在感知...",
    "Recognize": "识别",
    "Recognizes": "识别",
    "Recognizing...": "正在识别...",
    "Identify": "识别",
    "Identifies": "识别",
    "Identifying...": "正在识别...",
    "Distinguish": "区分",
    "Distinguishes": "区分",
    "Distinguishing...": "正在区分...",
    "Differentiate": "区分",
    "Differentiates": "区分",
    "Differentiating...": "正在区分...",
    "Discriminate": "区分",
    "Discriminates": "区分",
    "Discriminating...": "正在区分...",
    "Separate": "分离",
    "Separates": "分离",
    "Separating...": "正在分离...",
    "Isolate": "隔离",
    "Isolates": "隔离",
    "Isolating...": "正在隔离...",
    "Extract": "提取",
    "Extracts": "提取",
    "Extracting...": "正在提取...",
    "Pull out": "提取",
    "Pulls out": "提取",
    "Pulling out...": "正在提取...",
    "Draw out": "提取",
    "Draws out": "提取",
    "Drawing out...": "正在提取...",
    "Withdraw": "撤回",
    "Withdraws": "撤回",
    "Withdrawing...": "正在撤回...",
    "Removes": "移除",
    "Eliminate": "消除",
    "Eliminates": "消除",
    "Eliminating...": "正在消除...",
    "Eradicate": "根除",
    "Eradicates": "根除",
    "Eradicating...": "正在根除...",
    "Destroy": "销毁",
    "Destroys": "销毁",
    "Destroying...": "正在销毁...",
    "Deletes": "删除",
    "Deleting...": "正在删除...",
    "Drop": "删除",
    "Drops": "删除",
    "Dropping...": "正在删除...",
    "Clears": "清除",
    "Clearing...": "正在清除...",
    "Clean": "清理",
    "Cleans": "清理",
    "Cleaning...": "正在清理...",
    "Purge": "清除",
    "Purges": "清除",
    "Purging...": "正在清除...",
    "Flush": "刷新",
    "Flushes": "刷新",
    "Flushing...": "正在刷新...",
    "Resets": "重置",
    "Resetting...": "正在重置...",
    "Restart": "重启",
    "Restarts": "重启",
    "Restarting...": "正在重启...",
    "Reload": "重新加载",
    "Reloads": "重新加载",
    "Reloading...": "正在重新加载...",
    "Refreshes": "刷新",
    "Refreshing...": "正在刷新...",
    "Renew": "续期",
    "Renews": "续期",
    "Renewing...": "正在续期...",
    "Restores": "恢复",
    "Restoring...": "正在恢复...",
    "Recover": "恢复",
    "Recovers": "恢复",
    "Recovering...": "正在恢复...",
    "Repairs": "修复",
    "Repairing...": "正在修复...",
    "Fixes": "修复",
    "Fixing...": "正在修复...",
    "Mend": "修复",
    "Mends": "修复",
    "Mending...": "正在修复...",
    "Patch": "修补",
    "Patches": "修补",
    "Patching...": "正在修补...",
    "Resolves": "解决",
    "Resolving...": "正在解决...",
    "Solve": "解决",
    "Solves": "解决",
    "Solving...": "正在解决...",
    "Address": "处理",
    "Addresses": "处理",
    "Addressing...": "正在处理...",
    "Handle": "处理",
    "Handles": "处理",
    "Handling...": "正在处理...",
    "Manages": "管理",
    "Managing...": "正在管理...",
    "Administer": "管理",
    "Administers": "管理",
    "Administering...": "正在管理...",
    "Govern": "管理",
    "Governs": "管理",
    "Governing...": "正在管理...",
    "Controls": "控制",
    "Controlling...": "正在控制...",
    "Command": "命令",
    "Commands": "命令",
    "Commanding...": "正在命令...",
    "Direct": "指导",
    "Directs": "指导",
    "Directing...": "正在指导...",
    "Guide": "指导",
    "Guides": "指导",
    "Guiding...": "正在指导...",
    "Lead": "领导",
    "Leads": "领导",
    "Leading...": "正在领导...",
    "Steer": "引导",
    "Steers": "引导",
    "Steering...": "正在引导...",
    "Pilot": "引导",
    "Pilots": "引导",
    "Piloting...": "正在引导...",
    "Drive": "驱动",
    "Drives": "驱动",
    "Driving...": "正在驱动...",
    "Operate": "操作",
    "Operates": "操作",
    "Operating...": "正在操作...",
    "Works": "工作",
    "Working...": "正在工作...",
    "Functions": "功能",
    "Functioning...": "正在功能...",
    "Serves": "服务",
    "Serving...": "正在服务...",
    "Supports": "支持",
    "Supporting...": "正在支持...",
    "Helps": "帮助",
    "Helping...": "正在帮助...",
    "Assist": "协助",
    "Assists": "协助",
    "Assisting...": "正在协助...",
    "Aid": "帮助",
    "Aids": "帮助",
    "Aiding...": "正在帮助...",
    "Facilitate": "促进",
    "Facilitates": "促进",
    "Facilitating...": "正在促进...",
    "Enables": "启用",
    "Enabling...": "正在启用...",
    "Empower": "授权",
    "Empowers": "授权",
    "Empowering...": "正在授权...",
    "Allows": "允许",
    "Allowing...": "正在允许...",
    "Permit": "允许",
    "Permits": "允许",
    "Permitting...": "正在允许...",
    "Enable access": "启用访问",
    "Disable access": "禁用访问",
    "Grant": "授予",
    "Grants": "授予",
    "Granting...": "正在授予...",
    "Revokes": "撤销",
    "Revoking...": "正在撤销...",
    "Deny": "拒绝",
    "Denies": "拒绝",
    "Denying...": "正在拒绝...",
    "Refuse": "拒绝",
    "Refuses": "拒绝",
    "Refusing...": "正在拒绝...",
    "Rejects": "拒绝",
    "Rejecting...": "正在拒绝...",
    "Blocks": "阻止",
    "Blocking...": "正在阻止...",
    "Prevent": "阻止",
    "Prevents": "阻止",
    "Preventing...": "正在阻止...",
    "Stops": "停止",
    "Stopping...": "正在停止...",
    "Hinder": "阻碍",
    "Hinders": "阻碍",
    "Hindering...": "正在阻碍...",
    "Impede": "阻碍",
    "Impedes": "阻碍",
    "Impeding...": "正在阻碍...",
    "Obstruct": "阻碍",
    "Obstructs": "阻碍",
    "Obstructing...": "正在阻碍...",
    "Limits": "限制",
    "Limiting...": "正在限制...",
    "Restrict": "限制",
    "Restricts": "限制",
    "Restricting...": "正在限制...",
    "Constrain": "约束",
    "Constrains": "约束",
    "Constraining...": "正在约束...",
    "Bind": "绑定",
    "Binds": "绑定",
    "Binding...": "正在绑定...",
    "Tie": "绑定",
    "Ties": "绑定",
    "Tying...": "正在绑定...",
    "Attach": "附加",
    "Attaches": "附加",
    "Attaching...": "正在附加...",
    "Connects": "连接",
    "Connecting...": "正在连接...",
    "Link": "链接",
    "Links": "链接",
    "Linking...": "正在链接...",
    "Associate": "关联",
    "Associates": "关联",
    "Associating...": "正在关联...",
    "Relate": "关联",
    "Relates": "关联",
    "Relating...": "正在关联...",
    "Reference": "引用",
    "References": "引用",
    "Referencing...": "正在引用...",
    "Cite": "引用",
    "Cites": "引用",
    "Citing...": "正在引用...",
    "Quote": "引用",
    "Quotes": "引用",
    "Quoting...": "正在引用...",
    "Mention": "提及",
    "Mentions": "提及",
    "Mentioning...": "正在提及...",
    "Note": "注意",
    "Notes": "注意",
    "Noting...": "正在注意...",
    "Remark": "评论",
    "Remarks": "评论",
    "Remarking...": "正在评论...",
    "Comments": "评论",
    "Commenting...": "正在评论...",
    "Annotate": "注释",
    "Annotates": "注释",
    "Annotating...": "正在注释...",
    "Document": "文档",
    "Documents": "文档",
    "Documenting...": "正在文档...",
    "Records": "记录",
    "Recording...": "正在记录...",
    "Log": "日志",
    "Logs": "日志",
    "Logging...": "正在日志...",
    "Track": "跟踪",
    "Tracks": "跟踪",
    "Tracking...": "正在跟踪...",
    "Monitor": "监控",
    "Monitors": "监控",
    "Monitoring...": "正在监控...",
    "Watch": "观察",
    "Watches": "观察",
    "Watching...": "正在观察...",
    "Observe": "观察",
    "Observes": "观察",
    "Observing...": "正在观察...",
    "Supervise": "监督",
    "Supervises": "监督",
    "Supervising...": "正在监督...",
    "Oversee": "监督",
    "Oversees": "监督",
    "Overseeing...": "正在监督...",
    "Inspect": "检查",
    "Inspects": "检查",
    "Inspecting...": "正在检查...",
    "Examine": "检查",
    "Examines": "检查",
    "Examining...": "正在检查...",
    "Checks": "检查",
    "Checking...": "正在检查...",
    "Tests": "测试",
    "Testing...": "正在测试...",
    "Evaluate": "评估",
    "Evaluates": "评估",
    "Evaluating...": "正在评估...",
    "Assess": "评估",
    "Assesses": "评估",
    "Assessing...": "正在评估...",
    "Appraise": "评估",
    "Appraises": "评估",
    "Appraising...": "正在评估...",
    "Judge": "判断",
    "Judges": "判断",
    "Judging...": "正在判断...",
    "Measure": "测量",
    "Measures": "测量",
    "Measuring...": "正在测量...",
    "Quantify": "量化",
    "Quantifies": "量化",
    "Quantifying...": "正在量化...",
    "Calculate": "计算",
    "Calculates": "计算",
    "Calculating...": "正在计算...",
    "Compute": "计算",
    "Computes": "计算",
    "Computing...": "正在计算...",
    "Determine": "确定",
    "Determines": "确定",
    "Determining...": "正在确定...",
    "Decide": "决定",
    "Decides": "决定",
    "Deciding...": "正在决定...",
    "Conclude": "结论",
    "Concludes": "结论",
    "Concluding...": "正在结论...",
    "Deduce": "推断",
    "Deduces": "推断",
    "Deducing...": "正在推断...",
    "Infer": "推断",
    "Infers": "推断",
    "Inferring...": "正在推断...",
    "Derive": "推导",
    "Derives": "推导",
    "Deriving...": "正在推导...",
    "Induce": "归纳",
    "Induces": "归纳",
    "Inducing...": "正在归纳...",
    "Predict": "预测",
    "Predicts": "预测",
    "Predicting...": "正在预测...",
    "Forecast": "预测",
    "Forecasts": "预测",
    "Forecasting...": "正在预测...",
    "Project": "项目",
    "Projects": "项目",
    "Projecting...": "正在项目...",
    "Estimate": "估计",
    "Estimates": "估计",
    "Estimating...": "正在估计...",
    "Guess": "猜测",
    "Guesses": "猜测",
    "Guessing...": "正在猜测...",
    "Approximate": "近似",
    "Approximates": "近似",
    "Approximating...": "正在近似...",
    "Simulate": "模拟",
    "Simulates": "模拟",
    "Simulating...": "正在模拟...",
    "Emulate": "仿真",
    "Emulates": "仿真",
    "Emulating...": "正在仿真...",
    "Imitate": "模仿",
    "Imitates": "模仿",
    "Imitating...": "正在模仿...",
    "Mimic": "模仿",
    "Mimics": "模仿",
    "Mimicking...": "正在模仿...",
    "Model": "模型",
    "Models": "模型",
    "Modeling...": "正在建模...",
    "Prototype": "原型",
    "Prototypes": "原型",
    "Prototyping...": "正在原型...",
    "Mocks": "模拟",
    "Mocking...": "正在模拟...",
    "Fakes": "伪造",
    "Faking...": "正在伪造...",
    "Pretend": "假装",
    "Pretends": "假装",
    "Pretending...": "正在假装...",
    "Act": "行为",
    "Acts": "行为",
    "Acting...": "正在行为...",
    "Behave": "行为",
    "Behaves": "行为",
    "Behaving...": "正在行为...",
    "Performs": "执行",
    "Performing...": "正在执行...",
    "Do": "做",
    "Does": "做",
    "Doing...": "正在做...",
    "Done": "完成",
    "Did": "做了",
    "Doing": "正在做",
    "Will do": "将要做",
    "Would do": "会做",
    "Can do": "可以做",
    "Could do": "可能做",
    "Should do": "应该做",
    "Must do": "必须做",
    "Need to do": "需要做",
    "Have to do": "必须做",
    "Want to do": "想要做",
    "Like to do": "喜欢做",
    "Love to do": "热爱做",
    "Prefer to do": "喜欢做",
    "Choose to do": "选择做",
    "Decide to do": "决定做",
    "Plan to do": "计划做",
    "Intend to do": "打算做",
    "Aim to do": "旨在做",
    "Seek to do": "寻求做",
    "Try to do": "尝试做",
    "Attempt to do": "尝试做",
    "Endeavor to do": "努力做",
    "Strive to do": "努力做",
    "Struggle to do": "努力做",
    "Manage to do": "设法做",
    "Fail to do": "未能做",
    "Succeed in doing": "成功做",
    "Happen to do": "碰巧做",
    "Come to do": "来做",
    "Get to do": "得以做",
    "Learn to do": "学会做",
    "Begin to do": "开始做",
    "Start to do": "开始做",
    "Continue to do": "继续做",
    "Go on to do": "继续做",
    "Proceed to do": "继续做",
    "Stop doing": "停止做",
    "Quit doing": "停止做",
    "Give up doing": "放弃做",
    "Finish doing": "完成做",
    "Complete doing": "完成做",
    "End up doing": "最终做",
    "Wind up doing": "最终做",
    "Regret doing": "后悔做",
    "Remember doing": "记得做过",
    "Forget doing": "忘记做过",
    "Recall doing": "回忆做过",
    "Recollect doing": "回忆做过",
    "Imagine doing": "想象做",
    "Envision doing": "想象做",
    "Picture doing": "想象做",
    "Consider doing": "考虑做",
    "Contemplate doing": "考虑做",
    "Ponder doing": "考虑做",
    "Think about doing": "考虑做",
    "Dream of doing": "梦想做",
    "Fantasize about doing": "幻想做",
    "Enjoy doing": "喜欢做",
    "Like doing": "喜欢做",
    "Love doing": "热爱做",
    "Prefer doing": "喜欢做",
    "Fancy doing": "想要做",
    "Feel like doing": "想要做",
    "Avoid doing": "避免做",
    "Prevent doing": "阻止做",
    "Keep from doing": "阻止做",
    "Stop from doing": "阻止做",
    "Prohibit doing": "禁止做",
    "Forbid doing": "禁止做",
    "Risk doing": "冒险做",
    "Face doing": "面对做",
    "Escape doing": "逃脱做",
    "Miss doing": "错过做",
    "Resist doing": "抵制做",
    "Deny doing": "否认做",
    "Admit doing": "承认做",
    "Confess to doing": "承认做",
    "Acknowledge doing": "承认做",
    "Suggest doing": "建议做",
    "Recommend doing": "建议做",
    "Propose doing": "建议做",
    "Advise doing": "建议做",
    "Urge doing": "敦促做",
    "Encourage doing": "鼓励做",
    "Support doing": "支持做",
    "Oppose doing": "反对做",
    "Object to doing": "反对做",
    "Be used to doing": "习惯做",
    "Get used to doing": "习惯做",
    "Become used to doing": "习惯做",
    "Accustom to doing": "习惯做",
    "Be accustomed to doing": "习惯做",
    "Look forward to doing": "期待做",
    "Be worth doing": "值得做",
    "Be busy doing": "忙于做",
    "Have difficulty doing": "做有困难",
    "Have trouble doing": "做有麻烦",
    "Have problem doing": "做有问题",
    "Have a hard time doing": "做很艰难",
    "Have a good time doing": "做很愉快",
    "Have fun doing": "做很开心",
    "Spend time doing": "花时间做",
    "Waste time doing": "浪费时间做",
    "Kill time doing": "消磨时间做",
    "Save time doing": "节省时间做",
    "Take time doing": "花时间做",
    "Need time doing": "需要时间做",
    "Require doing": "需要做",
    "Want doing": "想要被做",
    "Deserve doing": "值得做",
    "Merit doing": "值得做",
    "Bear doing": "值得做",
    "Stand doing": "忍受做",
}

def translate_text(text):
    """Translate a single text string"""
    if text in TRANSLATIONS:
        return TRANSLATIONS[text]
    return text

def translate_dict(d):
    """Recursively translate dictionary values"""
    result = {}
    for key, value in d.items():
        if isinstance(value, dict):
            result[key] = translate_dict(value)
        elif isinstance(value, str):
            result[key] = translate_text(value)
        else:
            result[key] = value
    return result

# Translate zh.json
zh_translated = translate_dict(zh)

# Write translated file
with open(zh_path, 'w', encoding='utf-8') as f:
    json.dump(zh_translated, f, ensure_ascii=False, indent=2)

print("Translation complete!")
print(f"Updated {zh_path}")
